[package]
name = "access"
version = "1.0.0"
authors = []

[addresses]

[dev-addresses]

[dependencies.Somnia Framework]
git = "https://github.com/Somnia -labs/Somnia -framework.git"
rev = "mainnet"
subdir = "Somnia -framework"

[dev-dependencies]
